import Head from 'next/head'
// import {BsFillMoonStarsFill} from 'react/icons/bs'
// import {AiFillTwitterCircle, AiFillLinkedin}
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import { useState } from "react"


export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Joseph Worley Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Well, Hello There</h1>
            <ul className="flex items-center">
              <li>
                {/* <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-xl" /> */}
              </li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl" >Joseph Worley</h2>
            <h3 className="text-2xl py-2 md:text-3xl">Software Developer</h3>
            <p className="text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">Lorem</p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            {/* <AiFillTwitterCircle />
            <AiFillLinkedin /> */}
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            {/* <Image src={deved} layout="fill" objectFit="cover" /> */}
          </div>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              I began my coding <span className="text-teal-500">journey..</span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I began my coding journey..
            </p>
          </div>
          <div  className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Striking Designs</h3>
              <p className="py-2">Lorem empsum yoooo</p>
              <h4 className="py-4 text-teal-600">Languages and Technologies</h4>
              <p className="text-gray-800 py-1">HTML5</p>
              <p>CSS3</p>
              <p>JavaScript</p>
              <p>Node.js</p>
              <p>Next.js</p>
              <p>Express</p>
              <p>React</p>
            </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={code} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Striking Designs</h3>
                <p className="py-2">Lorem empsum yoooo</p>
                <h4 className="py-4 text-teal-600">Languages and Technologies</h4>
                <p className="text-gray-800 py-1">HTML5</p>
                <p>CSS3</p>
                <p>JavaScript</p>
                <p>Node.js</p>
                <p>Next.js</p>
                <p>Express</p>
                <p>React</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Striking Designs</h3>
              <p className="py-2">Lorem empsum yoooo</p>
              <h4 className="py-4 text-teal-600">Languages and Technologies</h4>
              <p className="text-gray-800 py-1">HTML5</p>
              <p>CSS3</p>
              <p>JavaScript</p>
              <p>Node.js</p>
              <p>Next.js</p>
              <p>Express</p>
              <p>React</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image 
                src={web1} 
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image 
                src={web2} 
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>

      </main>
    </div>
  )
}
